[package]
name = "trovr-storage"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
aws-sdk-s3 = { version = "1.150", default-features = false, features = ["rt-tokio", "default-https-client"] }
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false }
testcontainers.workspace = true
tokio = { workspace = true, features = ["time"] }
