#!/usr/bin/env bash
# Generates the git-ignored `.env` used by docker-compose: a JWT key pair for
# internal sign-in and random development credentials. Nothing here is meant
# for production. Usage: ./deploy/compose/init-env.sh [--force]
set -euo pipefail

cd "$(dirname "$0")/../.."
if [[ -f .env && "${1:-}" != "--force" ]]; then
  echo ".env already exists (use --force to replace it)" >&2
  exit 1
fi

private_key=$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)
public_key=$(openssl pkey -pubout <<<"$private_key")

umask 077
cat >.env <<ENV
# Generated by deploy/compose/init-env.sh — development only, never commit.
POSTGRES_PASSWORD=$(openssl rand -hex 16)
GARAGE_RPC_SECRET=$(openssl rand -hex 32)
GARAGE_ADMIN_TOKEN=$(openssl rand -hex 32)
S3_ACCESS_KEY_ID=GK$(openssl rand -hex 12)
S3_SECRET_ACCESS_KEY=$(openssl rand -hex 32)
JWT_PRIVATE_KEY_PEM="$private_key"
JWT_PUBLIC_KEY_PEM="$public_key"
ENV
echo "wrote .env"
