[package]
name = "trovr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
sqlx = { workspace = true, features = ["migrate"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
trovr-config = { version = "0.1.0", path = "../config" }

[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
uuid = { workspace = true }
