[package]
name = "trovr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "migrate", "uuid"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
trovr-config = { version = "0.1.0", path = "../config" }

[dev-dependencies]
testcontainers = "0.27.3"
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
uuid = "1.26.1"
