[package]
name = "trovr-metadata"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
chrono = "0.4.45"
sqlx.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
sqlx = { workspace = true, features = ["migrate"] }
testcontainers.workspace = true
testcontainers-modules.workspace = true
tokio.workspace = true
uuid = { workspace = true, features = ["v4"] }
