[package]
name = "trovr-metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
sqlx = { workspace = true, features = ["migrate"] }
testcontainers.workspace = true
testcontainers-modules.workspace = true
tokio.workspace = true
