/** User-facing text, kept in one place so a translation can be added later. */
export const strings = {
  appName: 'Trovr',
  loading: 'Loading…',
  signIn: 'Sign in',
  signInTitle: 'Sign in to Trovr',
  signInWithSso: 'Sign in with SSO',
  signOut: 'Sign out',
  or: 'or',
  email: 'Email',
  password: 'Password',
  name: 'Name',
  createAccount: 'Create account',
  createAnAccount: 'Create an account',
  createAccountTitle: 'Create your Trovr account',
  haveAnAccount: 'Already have an account?',
  noAccount: 'No account yet?',
  completingSignIn: 'Completing sign-in…',
  signInFailed: 'Sign-in could not be completed.',
  backToSignIn: 'Back to sign in',
  noSignInMethod: 'No sign-in method is enabled on this server.',
  myFiles: 'My files',
  sharedWithMe: 'Shared with me',
  trash: 'Trash',
  emptyFolder: 'This folder is empty.',
  notFound: 'Not found or no longer shared with you.',
  backToMyFiles: 'Back to My files',
  columns: { name: 'Name', size: 'Size', modified: 'Modified' },
  newFolder: 'New folder',
  create: 'Create',
  rename: 'Rename',
  move: 'Move',
  moveHere: 'Move here',
  moveToTrash: 'Move to trash',
  moveTitle: (name: string) => `Move “${name}”`,
  moveDescription: 'Choose the folder to move it into.',
  noSubfolders: 'No folders here.',
  renameTitle: (name: string) => `Rename “${name}”`,
  actionsFor: (name: string) => `Actions for ${name}`,
  movedToTrash: (name: string) => `Moved “${name}” to the trash.`,
  close: 'Close',
  share: {
    menu: 'Share',
    title: (name: string) => `Share “${name}”`,
    description: 'People you add can open it and everything inside it.',
    people: 'People',
    access: 'Access',
    accessFor: (name: string) => `Access for ${name}`,
    roles: { viewer: 'Viewer', editor: 'Editor' },
    submit: 'Share',
    remove: (name: string) => `Remove ${name}`,
    alreadyOwner: 'This person already owns it.',
    links: 'Public links',
    linkExpires: 'Link expires',
    expiry: { never: 'Never', day: 'In 1 day', week: 'In 7 days', month: 'In 30 days' },
    createLink: 'Create link',
    linkUrl: 'Public link',
    copyLink: 'Copy link',
    revokeLink: 'Revoke link',
    copied: 'Link copied.',
    copyFailed: 'The link could not be copied.',
    neverExpires: 'Never expires',
    expiresOn: (date: string) => `Expires ${date}`,
  },
  download: 'Download',
  versions: {
    menu: 'Versions',
    title: (name: string) => `Versions of “${name}”`,
    description: 'Every version stays downloadable.',
    name: (number: number) => `Version ${number}`,
    current: 'Current',
    upload: 'Upload a new version',
    download: (number: number) => `Download version ${number}`,
  },
  upload: 'Upload',
  uploadFiles: 'Upload files',
  uploads: {
    title: 'Uploads',
    waiting: 'Waiting…',
    finishing: 'Finishing…',
    done: 'Uploaded',
    retry: 'Retry',
    replace: 'Replace',
    skip: 'Skip',
    conflict: 'A file with this name already exists.',
    tooLarge: (limit: string) => `Larger than the ${limit} limit.`,
    dismiss: (name: string) => `Dismiss ${name}`,
    dropHere: 'Drop files to upload them here',
  },
  errors: {
    unexpected: 'Something went wrong. Please try again.',
    network_error: 'The server could not be reached.',
    invalid_credentials: 'Wrong email or password.',
    email_taken: 'An account already uses this email.',
    registration_disabled: 'Registration is disabled on this server.',
    identity_provider_unavailable: 'The identity provider is unavailable.',
    forbidden: 'You do not have enough access to do this.',
    not_found: 'Not found or no longer shared with you.',
    name_conflict: 'Something with this name already exists here.',
    invalid_name: 'This name is not allowed.',
    cycle_detected: 'A folder cannot be moved inside itself.',
    not_a_folder: 'The destination is not a folder.',
    not_a_file: 'This is not a file.',
    parent_trashed: 'Its folder is in the trash: restore the folder first.',
    not_trashed: 'This item is not in the trash.',
    storage_unavailable: 'File storage is unavailable. Please try again later.',
    upload_missing: 'The upload did not reach storage. Please try again.',
    upload_already_used: 'This upload was already used.',
    invalid_upload: 'This upload is not valid.',
    invalid_content: 'The file content is not valid.',
    user_not_found: 'No account uses this email.',
    ambiguous_user: 'Several accounts use this email.',
    storage_upload_failed: 'Storage refused the upload. Please try again.',
  },
} as const
