/** User-facing text, kept in one place so a translation can be added later. */
export const strings = {
  appName: 'Trovr',
  loading: 'Loading…',
  signIn: 'Sign in',
  signInTitle: 'Sign in to Trovr',
  signInWithSso: 'Sign in with SSO',
  signOut: 'Sign out',
  or: 'or',
  email: 'Email',
  password: 'Password',
  name: 'Name',
  createAccount: 'Create account',
  createAnAccount: 'Create an account',
  createAccountTitle: 'Create your Trovr account',
  haveAnAccount: 'Already have an account?',
  noAccount: 'No account yet?',
  completingSignIn: 'Completing sign-in…',
  signInFailed: 'Sign-in could not be completed.',
  backToSignIn: 'Back to sign in',
  noSignInMethod: 'No sign-in method is enabled on this server.',
  errors: {
    unexpected: 'Something went wrong. Please try again.',
    network_error: 'The server could not be reached.',
    invalid_credentials: 'Wrong email or password.',
    email_taken: 'An account already uses this email.',
    registration_disabled: 'Registration is disabled on this server.',
    identity_provider_unavailable: 'The identity provider is unavailable.',
  },
} as const
